[
	{ "id":"02.01", "nombre":"Obturacion c/ amalgama: cavidad simple - solo cara", "aplicaCara":true, "aplicaDiente":false },
	{ "id":"02.02", "nombre":"Obturacion c/ amalgama: cavidad compuesta - solo diente", "aplicaCara":false, "aplicaDiente":true },
	{ "id":"02.04", "nombre":"Obturacion c/amalgama: reconstrucciones - cara y diente", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"02.05", "nombre":"Obt.con Ionómero cav.simple - sin cara y sin diente", "aplicaCara":false, "aplicaDiente":false },
	{ "id":"02.06", "nombre":"Obt. con Ionómero", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"02.08", "nombre":"Obturacion c/resinas acrilicas: cavidad", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"02.09", "nombre":"Reconstruccion de angulos: dientes anter", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"02.10", "nombre":"Composite compuesto con tornillo en cond.", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"02.16", "nombre":"Lampara luz alogena", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"02.17", "nombre":"Lampara luz halógena", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"03.01", "nombre":"Trat. inflamatorio pulpar:UNIRR. (inc. Rx)", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"03.02", "nombre":"Trat. inflamatorio pulpar: MULTIRR.(inc. Rx)", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"03.05", "nombre":"Biopulpectomia parcial", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"03.06", "nombre":"Necropulpectomia parcial: MOMIFICACION", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.01.01", "nombre":"Incrustaciones: cavidad simple", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.01.02", "nombre":"Incrustaciones: cavidad compuesta o comp", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.01.03", "nombre":"Corona Forjada", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.01.04", "nombre":"Corona colada", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.01.05", "nombre":"Corona colada con frente estÚtico", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.01.06", "nombre":"Corona espiga", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.01.07", "nombre":"Corona colada reves. De acrilico", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.01.08", "nombre":"Perno muñon simple", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.01.09", "nombre":"Perno muñon seccionado", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.01.10", "nombre":"Tramo de puente colado", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.01.11", "nombre":"Corona de acrilico", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.01.12", "nombre":"Elemento provisorio: por unidad", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.01.13", "nombre":"Corona de porcelana sobre metal", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.01.14", "nombre":"Jacket de porcelana", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.02.01", "nombre":"Protesis de acrilico: hasta 4 dientes", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.02.02", "nombre":"Protesis de acrilico: de 5 o mts dientes", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.02.03", "nombre":"Colados en cromo cobalto: hasta 4 diente", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.02.04", "nombre":"Colados en cromo cobalto: de 5 o mts die", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.02.05", "nombre":"Protesis parcial inmediata", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.03.01", "nombre":"Protesis de acrilico superior", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.03.02", "nombre":"Protesis de acrilico inferior", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.03.03", "nombre":"Prot. Completa Inmediata Remov", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.03.04", "nombre":"Base colada para protesis completa", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.04.01", "nombre":"Compostura simple", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.04.02", "nombre":"Compostura con agregado de un diente", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.04.03", "nombre":"Compostura con agregado de un retenedor", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.04.04", "nombre":"Compostura con agregado de un diente y u", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.04.05", "nombre":"Diente subsiguiente: cada uno", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.04.06", "nombre":"Retenedor subsiguiente: cada uno", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.04.07", "nombre":"Retenedor en cromo con agregado de un di", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.04.08", "nombre":"Retencion subsiguiente", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.04.09", "nombre":"Carilla de acrilico", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.04.10", "nombre":"Rebasado de protesis: cada una", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.04.11", "nombre":"Cubeta individual", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.04.12", "nombre":"Levante de articulacion en acrilico tras", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"04.84.01", "nombre":"sdsd", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"05.00", "nombre":"Ficha de prevencion", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"05.01", "nombre":"Tartrectomia y cepillado mecanico", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"05.02", "nombre":"Cons. preventiva periodica (c/cepilla)", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"05.04", "nombre":"Enseñanzas de tÚcnicas de higiene bucal", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"05.05", "nombre":"Sellantes de puntos y fisuras. Por pieza", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"06.01", "nombre":"Consulta de estudio (sin RX extraoral)", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"06.02", "nombre":"Tratamiento de denticion primaria o mixt", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"06.03", "nombre":"Tratamiento de denticion permanente. Sin", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"06.04", "nombre":"Contencion (con aparatologÝa de contenci", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"07.01", "nombre":"Motivacion: hasta 3 consultas, incluida", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"07.02", "nombre":"Mantenedor de espacio fijo", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"07.03", "nombre":"Mantenedor de espacio removible", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"07.04", "nombre":"Trat. de dientes primarios con formocresol", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"07.05", "nombre":"Corona metalica de acero y similares", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"07.06", "nombre":"Traumatismo dentario", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"07.06.01", "nombre":"Reduccion de luxacion con inmovilizacion", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"07.06.02", "nombre":"Luxacion total (reimplante) e inmoviliza", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"07.06.03", "nombre":"Fractura coronaria de esmalte", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"07.06.04", "nombre":"Fractura amel. Corona proviso", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"08.01", "nombre":"Consulta de estudio-Diagnostico-Pronosti", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"08.02", "nombre":"Tratamiento de gingivitis marginal cronica", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"08.03", "nombre":"Trat. de periontoditis destructiva leve o sev", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"08.04", "nombre":"Trat. de periontoditis destructiva sever", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"08.05", "nombre":"Desgaste selctivo o armonizacion oclusal", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"08.06", "nombre":"Placas oclusales (temporarias) de acroli", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"09.01.01", "nombre":"Periapical: tecnica de cono corto o largo", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"09.01.02", "nombre":"Bite-Wing", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"09.01.03", "nombre":"Oclusal 6 cm.x 8 cm.", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"09.01.04", "nombre":"Media seriada de 7 peliculas", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"09.01.05", "nombre":"Seriada de 14 peliculas", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"09.02.04", "nombre":"Pantomografias", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"09.02.05", "nombre":"Teleradiografia cefalometrica", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.01", "nombre":"Extraccion dentaria", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.02", "nombre":"Plastica de comunicacion buco-sinusal", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.02.01", "nombre":"Alveol. correct. maxilar sup.", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.02.02", "nombre":"Apicectomía c/RX pre-post.", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.02.03", "nombre":"Extirp. de quistes pequeños", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.02.04", "nombre":"Ext. de dientes o res. c/rx", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.02.05", "nombre":"Radectomia c/RX post", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.02.06", "nombre":"Toma de mat. p/biop. c/dific.", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.02.07", "nombre":"Trat. de fract. dento-alv.comp", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.02.08", "nombre":"Trat. her. tej. blan. compleja", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.02.09", "nombre":"Vestib. de maxilar sup. e inf.", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.05", "nombre":"Reimplante dentario inmediato al traumat", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.06", "nombre":"Incision y drenaje de abcesos por via in", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.07", "nombre":"Biopsia por escision", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.08", "nombre":"Alargamiento quirurgico de la corona clo", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.09", "nombre":"Extr. dientes retenidos c/retencion OSEA", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.10", "nombre":"Germectomia", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.11", "nombre":"Liberacion de dientes retenidos", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.12", "nombre":"Apicectomia", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.13", "nombre":"Tratamiento de osteomielitis", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.14", "nombre":"Extraccion de cuerpo extraño", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.15", "nombre":"Alveleoctomia correctiva 6 zonas) por zo", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.16", "nombre":"Quist. o ext. de tum. tej. dur", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.16.01", "nombre":"Hasta 1 cm. de diámetro", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.16.03", "nombre":"Más de 3 cm.- de diámetro", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.17", "nombre":"Ext. de tumores en tejidos bla", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.17.01", "nombre":"Hasta 1 cm. de diámetro", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.17.02", "nombre":"De 1 a 3 cm. de diámetro", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.17.03", "nombre":"De mas de 3 cm. de diámetro", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"10.18", "nombre":"Ext. alv. ext. y restos rad.", "aplicaCara":true, "aplicaDiente":true },
	{ "id":"84.01.01", "nombre":"extraccion prueba de codigo"}
]