[
	{ "id":"02.01", "tratamiento":"Obturacion c/ amalgama: cavidad simple"},
	{ "id":"02.02", "tratamiento":"Obturacion c/ amalgama: cavidad compuesta"},
	{ "id":"02.04", "tratamiento":"Obturacion c/amalgama: reconstrucciones"},
	{ "id":"02.05", "tratamiento":"Obt.con Ionómero cav.simple"},
	{ "id":"02.06", "tratamiento":"Obt. con Ionómero"},
	{ "id":"02.08", "tratamiento":"Obturacion c/resinas acrilicas: cavidad"},
	{ "id":"02.09", "tratamiento":"Reconstruccion de angulos: dientes anter"},
	{ "id":"02.10", "tratamiento":"Composite compuesto con tornillo en cond."},
	{ "id":"02.16", "tratamiento":"Lampara luz alogena"},
	{ "id":"02.17", "tratamiento":"Lampara luz halógena"},
	{ "id":"03.01", "tratamiento":"Trat. inflamatorio pulpar:UNIRR. (inc. Rx)"},
	{ "id":"03.02", "tratamiento":"Trat. inflamatorio pulpar: MULTIRR.(inc. Rx)"},
	{ "id":"03.05", "tratamiento":"Biopulpectomia parcial"},
	{ "id":"03.06", "tratamiento":"Necropulpectomia parcial: MOMIFICACION"},
	{ "id":"04.01.01", "tratamiento":"Incrustaciones: cavidad simple"},
	{ "id":"04.01.02", "tratamiento":"Incrustaciones: cavidad compuesta o comp"},
	{ "id":"04.01.03", "tratamiento":"Corona Forjada"},
	{ "id":"04.01.04", "tratamiento":"Corona colada"},
	{ "id":"04.01.05", "tratamiento":"Corona colada con frente estÚtico"},
	{ "id":"04.01.06", "tratamiento":"Corona espiga"},
	{ "id":"04.01.07", "tratamiento":"Corona colada reves. De acrilico"},
	{ "id":"04.01.08", "tratamiento":"Perno muñon simple"},
	{ "id":"04.01.09", "tratamiento":"Perno muñon seccionado"},
	{ "id":"04.01.10", "tratamiento":"Tramo de puente colado"},
	{ "id":"04.01.11", "tratamiento":"Corona de acrilico"},
	{ "id":"04.01.12", "tratamiento":"Elemento provisorio: por unidad"},
	{ "id":"04.01.13", "tratamiento":"Corona de porcelana sobre metal"},
	{ "id":"04.01.14", "tratamiento":"Jacket de porcelana"},
	{ "id":"04.02.01", "tratamiento":"Protesis de acrilico: hasta 4 dientes"},
	{ "id":"04.02.02", "tratamiento":"Protesis de acrilico: de 5 o mts dientes"},
	{ "id":"04.02.03", "tratamiento":"Colados en cromo cobalto: hasta 4 diente"},
	{ "id":"04.02.04", "tratamiento":"Colados en cromo cobalto: de 5 o mts die"},
	{ "id":"04.02.05", "tratamiento":"Protesis parcial inmediata"},
	{ "id":"04.03.01", "tratamiento":"Protesis de acrilico superior"},
	{ "id":"04.03.02", "tratamiento":"Protesis de acrilico inferior"},
	{ "id":"04.03.03", "tratamiento":"Prot. Completa Inmediata Remov"},
	{ "id":"04.03.04", "tratamiento":"Base colada para protesis completa"},
	{ "id":"04.04.01", "tratamiento":"Compostura simple"},
	{ "id":"04.04.02", "tratamiento":"Compostura con agregado de un diente"},
	{ "id":"04.04.03", "tratamiento":"Compostura con agregado de un retenedor"},
	{ "id":"04.04.04", "tratamiento":"Compostura con agregado de un diente y u"},
	{ "id":"04.04.05", "tratamiento":"Diente subsiguiente: cada uno"},
	{ "id":"04.04.06", "tratamiento":"Retenedor subsiguiente: cada uno"},
	{ "id":"04.04.07", "tratamiento":"Retenedor en cromo con agregado de un di"},
	{ "id":"04.04.08", "tratamiento":"Retencion subsiguiente"},
	{ "id":"04.04.09", "tratamiento":"Carilla de acrilico"},
	{ "id":"04.04.10", "tratamiento":"Rebasado de protesis: cada una"},
	{ "id":"04.04.11", "tratamiento":"Cubeta individual"},
	{ "id":"04.04.12", "tratamiento":"Levante de articulacion en acrilico tras"},
	{ "id":"04.84.01", "tratamiento":"sdsd"},
	{ "id":"05.00", "tratamiento":"Ficha de prevencion"},
	{ "id":"05.01", "tratamiento":"Tartrectomia y cepillado mecanico"},
	{ "id":"05.02", "tratamiento":"Cons. preventiva periodica (c/cepilla)"},
	{ "id":"05.04", "tratamiento":"Enseñanzas de tÚcnicas de higiene bucal"},
	{ "id":"05.05", "tratamiento":"Sellantes de puntos y fisuras. Por pieza"},
	{ "id":"06.01", "tratamiento":"Consulta de estudio (sin RX extraoral)"},
	{ "id":"06.02", "tratamiento":"Tratamiento de denticion primaria o mixt"},
	{ "id":"06.03", "tratamiento":"Tratamiento de denticion permanente. Sin"},
	{ "id":"06.04", "tratamiento":"Contencion (con aparatologÝa de contenci"},
	{ "id":"07.01", "tratamiento":"Motivacion: hasta 3 consultas, incluida"},
	{ "id":"07.02", "tratamiento":"Mantenedor de espacio fijo"},
	{ "id":"07.03", "tratamiento":"Mantenedor de espacio removible"},
	{ "id":"07.04", "tratamiento":"Trat. de dientes primarios con formocresol"},
	{ "id":"07.05", "tratamiento":"Corona metalica de acero y similares"},
	{ "id":"07.06", "tratamiento":"Traumatismo dentario"},
	{ "id":"07.06.01", "tratamiento":"Reduccion de luxacion con inmovilizacion"},
	{ "id":"07.06.02", "tratamiento":"Luxacion total (reimplante) e inmoviliza"},
	{ "id":"07.06.03", "tratamiento":"Fractura coronaria de esmalte"},
	{ "id":"07.06.04", "tratamiento":"Fractura amel. Corona proviso"},
	{ "id":"08.01", "tratamiento":"Consulta de estudio-Diagnostico-Pronosti"},
	{ "id":"08.02", "tratamiento":"Tratamiento de gingivitis marginal cronica"},
	{ "id":"08.03", "tratamiento":"Trat. de periontoditis destructiva leve o sev"},
	{ "id":"08.04", "tratamiento":"Trat. de periontoditis destructiva sever"},
	{ "id":"08.05", "tratamiento":"Desgaste selctivo o armonizacion oclusal"},
	{ "id":"08.06", "tratamiento":"Placas oclusales (temporarias) de acroli"},
	{ "id":"09.01.01", "tratamiento":"Periapical: tecnica de cono corto o largo"},
	{ "id":"09.01.02", "tratamiento":"Bite-Wing"},
	{ "id":"09.01.03", "tratamiento":"Oclusal 6 cm.x 8 cm."},
	{ "id":"09.01.04", "tratamiento":"Media seriada de 7 peliculas"},
	{ "id":"09.01.05", "tratamiento":"Seriada de 14 peliculas"},
	{ "id":"09.02.04", "tratamiento":"Pantomografias"},
	{ "id":"09.02.05", "tratamiento":"Teleradiografia cefalometrica"},
	{ "id":"10.01", "tratamiento":"Extraccion dentaria"},
	{ "id":"10.02", "tratamiento":"Plastica de comunicacion buco-sinusal"},
	{ "id":"10.02.01", "tratamiento":"Alveol. correct. maxilar sup."},
	{ "id":"10.02.02", "tratamiento":"Apicectomía c/RX pre-post."},
	{ "id":"10.02.03", "tratamiento":"Extirp. de quistes pequeños"},
	{ "id":"10.02.04", "tratamiento":"Ext. de dientes o res. c/rx"},
	{ "id":"10.02.05", "tratamiento":"Radectomia c/RX post"},
	{ "id":"10.02.06", "tratamiento":"Toma de mat. p/biop. c/dific."},
	{ "id":"10.02.07", "tratamiento":"Trat. de fract. dento-alv.comp"},
	{ "id":"10.02.08", "tratamiento":"Trat. her. tej. blan. compleja"},
	{ "id":"10.02.09", "tratamiento":"Vestib. de maxilar sup. e inf."},
	{ "id":"10.05", "tratamiento":"Reimplante dentario inmediato al traumat"},
	{ "id":"10.06", "tratamiento":"Incision y drenaje de abcesos por via in"},
	{ "id":"10.07", "tratamiento":"Biopsia por escision"},
	{ "id":"10.08", "tratamiento":"Alargamiento quirurgico de la corona clo"},
	{ "id":"10.09", "tratamiento":"Extr. dientes retenidos c/retencion OSEA"},
	{ "id":"10.10", "tratamiento":"Germectomia"},
	{ "id":"10.11", "tratamiento":"Liberacion de dientes retenidos"},
	{ "id":"10.12", "tratamiento":"Apicectomia"},
	{ "id":"10.13", "tratamiento":"Tratamiento de osteomielitis"},
	{ "id":"10.14", "tratamiento":"Extraccion de cuerpo extraño"},
	{ "id":"10.15", "tratamiento":"Alveleoctomia correctiva 6 zonas) por zo"},
	{ "id":"10.16", "tratamiento":"Quist. o ext. de tum. tej. dur"},
	{ "id":"10.16.01", "tratamiento":"Hasta 1 cm. de diámetro"},
	{ "id":"10.16.03", "tratamiento":"Más de 3 cm.- de diámetro"},
	{ "id":"10.17", "tratamiento":"Ext. de tumores en tejidos bla"},
	{ "id":"10.17.01", "tratamiento":"Hasta 1 cm. de diámetro"},
	{ "id":"10.17.02", "tratamiento":"De 1 a 3 cm. de diámetro"},
	{ "id":"10.17.03", "tratamiento":"De mas de 3 cm. de diámetro"},
	{ "id":"10.18", "tratamiento":"Ext. alv. ext. y restos rad."},
	{ "id":"84.01.01", "tratamiento":"extraccion prueba de codigo"}
]